import type { CategoryId, Dish } from "@/lib/catalog";

export const BAKETREE = {
  slug: "baketree",
  name: "BakeTree Resto Cafe",
  tagline: "Fried rice, shawarma, al faham, dosa & shakes — Palarivattom",
  cuisine: "Cafe, Chinese, Arabian, Burgers",
  city: "Kochi",
  area: "Palarivattom",
  address: "Puthiya Road, Palarivattom, Kochi",
  phone: "9895109707",
  email: "baketree@gmail.com",
  whatsapp: "9895109707",
  hours: "9:00 AM – 9:00 PM",
  rating: 4.1,
  distanceKm: 3.2,
  logo: "/images/baketree/logo.jpg",
  cover: "/images/baketree/7111.jpg",
} as const;

export type BaketreeCategoryId =
  | "fried-rice"
  | "noodles"
  | "burgers"
  | "wings"
  | "curries"
  | "dosa"
  | "al-faham"
  | "shawarma"
  | "combos"
  | "drinks";

export type BaketreeDish = Dish & {
  baketreeCategory: BaketreeCategoryId;
};

export const BAKETREE_CATEGORIES: {
  id: BaketreeCategoryId;
  label: string;
  blurb: string;
  image: string;
}[] = [
  {
    id: "fried-rice",
    label: "Fried Rice",
    blurb: "Wok-tossed rice, full or half plates.",
    image: "/images/baketree/7078.jpg",
  },
  {
    id: "noodles",
    label: "Noodles",
    blurb: "Hakka-style noodles, full or half.",
    image: "/images/baketree/7086.jpg",
  },
  {
    id: "burgers",
    label: "Burgers",
    blurb: "Cafe burgers off the BakeTree griddle.",
    image: "/images/baketree/7094.jpg",
  },
  {
    id: "wings",
    label: "Wings",
    blurb: "Crispy chicken wings, plate or 2-piece.",
    image: "/images/baketree/7097.jpg",
  },
  {
    id: "curries",
    label: "Curries",
    blurb: "Chinese-Indian curries to pair with rice or porotta.",
    image: "/images/baketree/7099.jpg",
  },
  {
    id: "dosa",
    label: "Dosa",
    blurb: "Crisp dosas from the tawa.",
    image: "/images/baketree/7108.jpg",
  },
  {
    id: "al-faham",
    label: "Al Faham",
    blurb: "Charcoal al faham, classic and peri peri.",
    image: "/images/baketree/7111.jpg",
  },
  {
    id: "shawarma",
    label: "Shawarma",
    blurb: "Rolls and plates, rumali and full-meat.",
    image: "/images/baketree/7118.jpg",
  },
  {
    id: "combos",
    label: "Combos",
    blurb: "Rice, porotta, shawarma and grill meals.",
    image: "/images/baketree/7127.jpg",
  },
  {
    id: "drinks",
    label: "Drinks",
    blurb: "Pineapple lime, Sharjah shake, mango juice and tea.",
    image: "/images/baketree/7142.jpg",
  },
];

const BASE = {
  restaurant: BAKETREE.name,
  cuisine: BAKETREE.cuisine,
  rating: BAKETREE.rating,
  distanceKm: BAKETREE.distanceKm,
  keralaClassic: false,
  freeDelivery: true,
  storeHref: "/baketree/",
} as const;

export const BAKETREE_DISHES: BaketreeDish[] = [
  {
    id: "baketree-7078",
    name: "Chicken Fried Rice - Full",
    ...BASE,
    baketreeCategory: "fried-rice",
    category: "meals" as CategoryId,
    price: 160,
    aggregatorPrice: 208,
    etaMin: 20,
    etaMax: 28,
    veg: false,
    image: "/images/baketree/7078.jpg",
  },
  {
    id: "baketree-7079",
    name: "Chicken Fried Rice - Half",
    ...BASE,
    baketreeCategory: "fried-rice",
    category: "meals" as CategoryId,
    price: 120,
    aggregatorPrice: 156,
    etaMin: 20,
    etaMax: 28,
    veg: false,
    image: "/images/baketree/7079.jpg",
  },
  {
    id: "baketree-7080",
    name: "Egg Fried Rice - Full",
    ...BASE,
    baketreeCategory: "fried-rice",
    category: "meals" as CategoryId,
    price: 130,
    aggregatorPrice: 169,
    etaMin: 20,
    etaMax: 28,
    veg: false,
    image: "/images/baketree/7080.jpg",
  },
  {
    id: "baketree-7081",
    name: "Egg Fried Rice - Half",
    ...BASE,
    baketreeCategory: "fried-rice",
    category: "meals" as CategoryId,
    price: 90,
    aggregatorPrice: 117,
    etaMin: 20,
    etaMax: 28,
    veg: false,
    image: "/images/baketree/7081.jpg",
  },
  {
    id: "baketree-7082",
    name: "Veg Fried Rice - Full",
    ...BASE,
    baketreeCategory: "fried-rice",
    category: "meals" as CategoryId,
    price: 120,
    aggregatorPrice: 156,
    etaMin: 20,
    etaMax: 28,
    veg: true,
    image: "/images/baketree/7082.jpg",
  },
  {
    id: "baketree-7083",
    name: "Veg Fried Rice - Half",
    ...BASE,
    baketreeCategory: "fried-rice",
    category: "meals" as CategoryId,
    price: 80,
    aggregatorPrice: 104,
    etaMin: 20,
    etaMax: 28,
    veg: true,
    image: "/images/baketree/7083.jpg",
  },
  {
    id: "baketree-7084",
    name: "Mixed Fried Rice - Full",
    ...BASE,
    baketreeCategory: "fried-rice",
    category: "meals" as CategoryId,
    price: 170,
    aggregatorPrice: 221,
    etaMin: 20,
    etaMax: 28,
    veg: false,
    image: "/images/baketree/7084.jpg",
  },
  {
    id: "baketree-7085",
    name: "Mixed Fried Rice - Half",
    ...BASE,
    baketreeCategory: "fried-rice",
    category: "meals" as CategoryId,
    price: 130,
    aggregatorPrice: 169,
    etaMin: 20,
    etaMax: 28,
    veg: false,
    image: "/images/baketree/7085.jpg",
  },
  {
    id: "baketree-7086",
    name: "Chicken Noodles - Full",
    ...BASE,
    baketreeCategory: "noodles",
    category: "meals" as CategoryId,
    price: 160,
    aggregatorPrice: 208,
    etaMin: 20,
    etaMax: 28,
    veg: false,
    image: "/images/baketree/7086.jpg",
  },
  {
    id: "baketree-7087",
    name: "Chicken Noodles - Half",
    ...BASE,
    baketreeCategory: "noodles",
    category: "meals" as CategoryId,
    price: 120,
    aggregatorPrice: 156,
    etaMin: 20,
    etaMax: 28,
    veg: false,
    image: "/images/baketree/7087.jpg",
  },
  {
    id: "baketree-7088",
    name: "Egg Noodles - Full",
    ...BASE,
    baketreeCategory: "noodles",
    category: "meals" as CategoryId,
    price: 130,
    aggregatorPrice: 169,
    etaMin: 20,
    etaMax: 28,
    veg: false,
    image: "/images/baketree/7088.jpg",
  },
  {
    id: "baketree-7089",
    name: "Egg Noodles - Half",
    ...BASE,
    baketreeCategory: "noodles",
    category: "meals" as CategoryId,
    price: 90,
    aggregatorPrice: 117,
    etaMin: 20,
    etaMax: 28,
    veg: false,
    image: "/images/baketree/7089.jpg",
  },
  {
    id: "baketree-7090",
    name: "Veg Noodles - Full",
    ...BASE,
    baketreeCategory: "noodles",
    category: "meals" as CategoryId,
    price: 120,
    aggregatorPrice: 156,
    etaMin: 20,
    etaMax: 28,
    veg: true,
    image: "/images/baketree/7090.jpg",
  },
  {
    id: "baketree-7091",
    name: "Veg Noodles - Half",
    ...BASE,
    baketreeCategory: "noodles",
    category: "meals" as CategoryId,
    price: 80,
    aggregatorPrice: 104,
    etaMin: 20,
    etaMax: 28,
    veg: true,
    image: "/images/baketree/7091.jpg",
  },
  {
    id: "baketree-7092",
    name: "Mixed Noodle - Full",
    ...BASE,
    baketreeCategory: "noodles",
    category: "meals" as CategoryId,
    price: 170,
    aggregatorPrice: 221,
    etaMin: 20,
    etaMax: 28,
    veg: false,
    image: "/images/baketree/7092.jpg",
  },
  {
    id: "baketree-7093",
    name: "Mixed Noodle - Half",
    ...BASE,
    baketreeCategory: "noodles",
    category: "meals" as CategoryId,
    price: 130,
    aggregatorPrice: 169,
    etaMin: 20,
    etaMax: 28,
    veg: false,
    image: "/images/baketree/7093.jpg",
  },
  {
    id: "baketree-7094",
    name: "Chicken Burger",
    ...BASE,
    baketreeCategory: "burgers",
    category: "burgers" as CategoryId,
    price: 110,
    aggregatorPrice: 143,
    etaMin: 16,
    etaMax: 22,
    veg: false,
    image: "/images/baketree/7094.jpg",
  },
  {
    id: "baketree-7095",
    name: "Veg Burger",
    ...BASE,
    baketreeCategory: "burgers",
    category: "burgers" as CategoryId,
    price: 70,
    aggregatorPrice: 91,
    etaMin: 16,
    etaMax: 22,
    veg: true,
    image: "/images/baketree/7095.jpg",
  },
  {
    id: "baketree-7096",
    name: "Chicken Cheese Burger",
    ...BASE,
    baketreeCategory: "burgers",
    category: "burgers" as CategoryId,
    price: 130,
    aggregatorPrice: 169,
    etaMin: 16,
    etaMax: 22,
    veg: false,
    image: "/images/baketree/7096.jpg",
  },
  {
    id: "baketree-7097",
    name: "Wings Plate",
    ...BASE,
    baketreeCategory: "wings",
    category: "burgers" as CategoryId,
    price: 120,
    aggregatorPrice: 156,
    etaMin: 16,
    etaMax: 22,
    veg: false,
    image: "/images/baketree/7097.jpg",
  },
  {
    id: "baketree-7098",
    name: "Wings 2 PC",
    ...BASE,
    baketreeCategory: "wings",
    category: "burgers" as CategoryId,
    price: 70,
    aggregatorPrice: 91,
    etaMin: 16,
    etaMax: 22,
    veg: false,
    image: "/images/baketree/7098.jpg",
  },
  {
    id: "baketree-7099",
    name: "Chilly Chicken - Full",
    ...BASE,
    baketreeCategory: "curries",
    category: "meals" as CategoryId,
    price: 260,
    aggregatorPrice: 338,
    etaMin: 18,
    etaMax: 26,
    veg: false,
    image: "/images/baketree/7099.jpg",
  },
  {
    id: "baketree-7100",
    name: "Chilly Chicken - Half",
    ...BASE,
    baketreeCategory: "curries",
    category: "meals" as CategoryId,
    price: 150,
    aggregatorPrice: 195,
    etaMin: 18,
    etaMax: 26,
    veg: false,
    image: "/images/baketree/7100.jpg",
  },
  {
    id: "baketree-7101",
    name: "Beef Curry",
    ...BASE,
    baketreeCategory: "curries",
    category: "meals" as CategoryId,
    price: 150,
    aggregatorPrice: 195,
    etaMin: 18,
    etaMax: 26,
    veg: false,
    image: "/images/baketree/7101.jpg",
  },
  {
    id: "baketree-7102",
    name: "Chilly Gobi - Full",
    ...BASE,
    baketreeCategory: "curries",
    category: "meals" as CategoryId,
    price: 170,
    aggregatorPrice: 221,
    etaMin: 18,
    etaMax: 26,
    veg: true,
    image: "/images/baketree/7102.jpg",
  },
  {
    id: "baketree-7103",
    name: "Chilly Gobi - Half",
    ...BASE,
    baketreeCategory: "curries",
    category: "meals" as CategoryId,
    price: 100,
    aggregatorPrice: 130,
    etaMin: 18,
    etaMax: 26,
    veg: true,
    image: "/images/baketree/7103.jpg",
  },
  {
    id: "baketree-7104",
    name: "Egg Curry",
    ...BASE,
    baketreeCategory: "curries",
    category: "meals" as CategoryId,
    price: 40,
    aggregatorPrice: 52,
    etaMin: 18,
    etaMax: 26,
    veg: false,
    image: "/images/baketree/7104.jpg",
  },
  {
    id: "baketree-7105",
    name: "Chilly Paneer - Full",
    ...BASE,
    baketreeCategory: "curries",
    category: "meals" as CategoryId,
    price: 220,
    aggregatorPrice: 286,
    etaMin: 18,
    etaMax: 26,
    veg: true,
    image: "/images/baketree/7105.jpg",
  },
  {
    id: "baketree-7106",
    name: "Chilly Paneer - Half",
    ...BASE,
    baketreeCategory: "curries",
    category: "meals" as CategoryId,
    price: 130,
    aggregatorPrice: 169,
    etaMin: 18,
    etaMax: 26,
    veg: true,
    image: "/images/baketree/7106.jpg",
  },
  {
    id: "baketree-7107",
    name: "Thattu Dosa",
    ...BASE,
    baketreeCategory: "dosa",
    category: "meals" as CategoryId,
    price: 60,
    aggregatorPrice: 78,
    etaMin: 12,
    etaMax: 18,
    veg: true,
    image: "/images/baketree/7107.jpg",
    keralaClassic: true,
  },
  {
    id: "baketree-7108",
    name: "Masala Dosa",
    ...BASE,
    baketreeCategory: "dosa",
    category: "meals" as CategoryId,
    price: 90,
    aggregatorPrice: 117,
    etaMin: 12,
    etaMax: 18,
    veg: true,
    image: "/images/baketree/7108.jpg",
    keralaClassic: true,
  },
  {
    id: "baketree-7109",
    name: "Ghee Roast",
    ...BASE,
    baketreeCategory: "dosa",
    category: "meals" as CategoryId,
    price: 90,
    aggregatorPrice: 117,
    etaMin: 12,
    etaMax: 18,
    veg: true,
    image: "/images/baketree/7109.jpg",
    keralaClassic: true,
  },
  {
    id: "baketree-7110",
    name: "Egg Dosa",
    ...BASE,
    baketreeCategory: "dosa",
    category: "meals" as CategoryId,
    price: 100,
    aggregatorPrice: 130,
    etaMin: 12,
    etaMax: 18,
    veg: false,
    image: "/images/baketree/7110.jpg",
  },
  {
    id: "baketree-7111",
    name: "Al Faham - Full",
    ...BASE,
    baketreeCategory: "al-faham",
    category: "grills" as CategoryId,
    price: 500,
    aggregatorPrice: 650,
    etaMin: 28,
    etaMax: 36,
    veg: false,
    image: "/images/baketree/7111.jpg",
    badge: "Live kitchen",
  },
  {
    id: "baketree-7112",
    name: "Al Faham - Half",
    ...BASE,
    baketreeCategory: "al-faham",
    category: "grills" as CategoryId,
    price: 270,
    aggregatorPrice: 351,
    etaMin: 28,
    etaMax: 36,
    veg: false,
    image: "/images/baketree/7112.jpg",
  },
  {
    id: "baketree-7113",
    name: "Al Faham - Quarter",
    ...BASE,
    baketreeCategory: "al-faham",
    category: "grills" as CategoryId,
    price: 140,
    aggregatorPrice: 182,
    etaMin: 28,
    etaMax: 36,
    veg: false,
    image: "/images/baketree/7113.jpg",
  },
  {
    id: "baketree-7114",
    name: "Peri Peri Al Faham - Full",
    ...BASE,
    baketreeCategory: "al-faham",
    category: "grills" as CategoryId,
    price: 540,
    aggregatorPrice: 702,
    etaMin: 28,
    etaMax: 36,
    veg: false,
    image: "/images/baketree/7114.jpg",
  },
  {
    id: "baketree-7115",
    name: "Peri Peri Al Faham - Half",
    ...BASE,
    baketreeCategory: "al-faham",
    category: "grills" as CategoryId,
    price: 290,
    aggregatorPrice: 377,
    etaMin: 28,
    etaMax: 36,
    veg: false,
    image: "/images/baketree/7115.jpg",
  },
  {
    id: "baketree-7116",
    name: "Peri Peri Al Faham - Quarter",
    ...BASE,
    baketreeCategory: "al-faham",
    category: "grills" as CategoryId,
    price: 150,
    aggregatorPrice: 195,
    etaMin: 28,
    etaMax: 36,
    veg: false,
    image: "/images/baketree/7116.jpg",
  },
  {
    id: "baketree-7117",
    name: "Shawarma Roll",
    ...BASE,
    baketreeCategory: "shawarma",
    category: "grills" as CategoryId,
    price: 100,
    aggregatorPrice: 130,
    etaMin: 16,
    etaMax: 22,
    veg: false,
    image: "/images/baketree/7117.jpg",
  },
  {
    id: "baketree-7118",
    name: "Shawarma Plate",
    ...BASE,
    baketreeCategory: "shawarma",
    category: "grills" as CategoryId,
    price: 140,
    aggregatorPrice: 182,
    etaMin: 16,
    etaMax: 22,
    veg: false,
    image: "/images/baketree/7118.jpg",
    badge: "Direct price",
  },
  {
    id: "baketree-7119",
    name: "Shawarma Rumali Roll",
    ...BASE,
    baketreeCategory: "shawarma",
    category: "grills" as CategoryId,
    price: 130,
    aggregatorPrice: 169,
    etaMin: 16,
    etaMax: 22,
    veg: false,
    image: "/images/baketree/7119.jpg",
  },
  {
    id: "baketree-7120",
    name: "Shawarma Rumali Plate",
    ...BASE,
    baketreeCategory: "shawarma",
    category: "grills" as CategoryId,
    price: 160,
    aggregatorPrice: 208,
    etaMin: 16,
    etaMax: 22,
    veg: false,
    image: "/images/baketree/7120.jpg",
  },
  {
    id: "baketree-7121",
    name: "Shawarma Full Meat Roll",
    ...BASE,
    baketreeCategory: "shawarma",
    category: "grills" as CategoryId,
    price: 160,
    aggregatorPrice: 208,
    etaMin: 16,
    etaMax: 22,
    veg: false,
    image: "/images/baketree/7121.jpg",
  },
  {
    id: "baketree-7122",
    name: "Shawarma Full Meat Plate",
    ...BASE,
    baketreeCategory: "shawarma",
    category: "grills" as CategoryId,
    price: 190,
    aggregatorPrice: 247,
    etaMin: 16,
    etaMax: 22,
    veg: false,
    image: "/images/baketree/7122.jpg",
  },
  {
    id: "baketree-7123",
    name: "Chicken Fried Rice + Chilli Chicken",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 130,
    aggregatorPrice: 169,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7123.jpg",
  },
  {
    id: "baketree-7124",
    name: "Chicken Fried Rice + Chilli Chicken + Pineapple Lime",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 150,
    aggregatorPrice: 195,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7124.jpg",
  },
  {
    id: "baketree-7125",
    name: "Ghee Rice + Beef",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 130,
    aggregatorPrice: 169,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7125.jpg",
  },
  {
    id: "baketree-7126",
    name: "Ghee Rice + Beef + Pineapple Lime",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 150,
    aggregatorPrice: 195,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7126.jpg",
  },
  {
    id: "baketree-7127",
    name: "Alfaham + Kabsa Rice",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 180,
    aggregatorPrice: 234,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7127.jpg",
    badge: "House combo",
  },
  {
    id: "baketree-7128",
    name: "Alfaham + Kabsa Rice + Pineapple Lime",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 200,
    aggregatorPrice: 260,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7128.jpg",
  },
  {
    id: "baketree-7129",
    name: "Shawaya + Kabsa Rice",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 180,
    aggregatorPrice: 234,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7129.jpg",
  },
  {
    id: "baketree-7130",
    name: "Shawaya + Kabsa Rice + Pineapple Lime",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 200,
    aggregatorPrice: 260,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7130.jpg",
  },
  {
    id: "baketree-7131",
    name: "Shawarma Roll + Sharjah Shake",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 160,
    aggregatorPrice: 208,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7131.jpg",
  },
  {
    id: "baketree-7132",
    name: "Shawarma Plate + Pineapple Lime",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 160,
    aggregatorPrice: 208,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7132.jpg",
  },
  {
    id: "baketree-7133",
    name: "Porotta + Chilli Chicken",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 140,
    aggregatorPrice: 182,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7133.jpg",
  },
  {
    id: "baketree-7134",
    name: "Porotta + Beef Curry",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 140,
    aggregatorPrice: 182,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7134.jpg",
  },
  {
    id: "baketree-7135",
    name: "Chappati + Chilli Chicken",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 140,
    aggregatorPrice: 182,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7135.jpg",
  },
  {
    id: "baketree-7136",
    name: "Chappati + Beef Curry",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 140,
    aggregatorPrice: 182,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7136.jpg",
  },
  {
    id: "baketree-7137",
    name: "Chicken Strips + Sharjah Shake",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 170,
    aggregatorPrice: 221,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7137.jpg",
  },
  {
    id: "baketree-7138",
    name: "Chicken Strips + French Fries",
    ...BASE,
    baketreeCategory: "combos",
    category: "burgers" as CategoryId,
    price: 180,
    aggregatorPrice: 234,
    etaMin: 22,
    etaMax: 30,
    veg: false,
    image: "/images/baketree/7138.jpg",
  },
  {
    id: "baketree-7139",
    name: "Pineapple Lime - Glass",
    ...BASE,
    baketreeCategory: "drinks",
    category: "coffee-dessert" as CategoryId,
    price: 30,
    aggregatorPrice: 39,
    etaMin: 10,
    etaMax: 16,
    veg: true,
    image: "/images/baketree/7139.jpg",
  },
  {
    id: "baketree-7140",
    name: "Pineapple Lime - 1/2 Ltr",
    ...BASE,
    baketreeCategory: "drinks",
    category: "coffee-dessert" as CategoryId,
    price: 60,
    aggregatorPrice: 78,
    etaMin: 10,
    etaMax: 16,
    veg: true,
    image: "/images/baketree/7140.jpg",
  },
  {
    id: "baketree-7141",
    name: "Pineapple Lime - 1 Ltr",
    ...BASE,
    baketreeCategory: "drinks",
    category: "coffee-dessert" as CategoryId,
    price: 120,
    aggregatorPrice: 156,
    etaMin: 10,
    etaMax: 16,
    veg: true,
    image: "/images/baketree/7141.jpg",
  },
  {
    id: "baketree-7142",
    name: "Sharjah Shake - Glass",
    ...BASE,
    baketreeCategory: "drinks",
    category: "coffee-dessert" as CategoryId,
    price: 70,
    aggregatorPrice: 91,
    etaMin: 10,
    etaMax: 16,
    veg: true,
    image: "/images/baketree/7142.jpg",
    badge: "Cafe favourite",
  },
  {
    id: "baketree-7143",
    name: "Sharjah Shake - 1/2 Ltr",
    ...BASE,
    baketreeCategory: "drinks",
    category: "coffee-dessert" as CategoryId,
    price: 120,
    aggregatorPrice: 156,
    etaMin: 10,
    etaMax: 16,
    veg: true,
    image: "/images/baketree/7143.jpg",
  },
  {
    id: "baketree-7144",
    name: "Sharjah Shake - 1 Ltr",
    ...BASE,
    baketreeCategory: "drinks",
    category: "coffee-dessert" as CategoryId,
    price: 210,
    aggregatorPrice: 273,
    etaMin: 10,
    etaMax: 16,
    veg: true,
    image: "/images/baketree/7144.jpg",
  },
  {
    id: "baketree-7145",
    name: "Mango Juice - Glass",
    ...BASE,
    baketreeCategory: "drinks",
    category: "coffee-dessert" as CategoryId,
    price: 70,
    aggregatorPrice: 91,
    etaMin: 10,
    etaMax: 16,
    veg: true,
    image: "/images/baketree/7145.jpg",
  },
  {
    id: "baketree-7146",
    name: "Mango Juice - 1/2 Ltr",
    ...BASE,
    baketreeCategory: "drinks",
    category: "coffee-dessert" as CategoryId,
    price: 120,
    aggregatorPrice: 156,
    etaMin: 10,
    etaMax: 16,
    veg: true,
    image: "/images/baketree/7146.jpg",
  },
  {
    id: "baketree-7147",
    name: "Mango Juice - 1 Ltr",
    ...BASE,
    baketreeCategory: "drinks",
    category: "coffee-dessert" as CategoryId,
    price: 210,
    aggregatorPrice: 273,
    etaMin: 10,
    etaMax: 16,
    veg: true,
    image: "/images/baketree/7147.jpg",
  },
  {
    id: "baketree-7150",
    name: "Tea",
    ...BASE,
    baketreeCategory: "drinks",
    category: "coffee-dessert" as CategoryId,
    price: 15,
    aggregatorPrice: 20,
    etaMin: 10,
    etaMax: 16,
    veg: true,
    image: "/images/baketree/7150.jpg",
    keralaClassic: true,
  },
];

export const BAKETREE_FEATURED_IDS = [
  "baketree-7111",
  "baketree-7118",
  "baketree-7094",
  "baketree-7127",
  "baketree-7142",
] as const;

export const BAKETREE_FEATURED: BaketreeDish[] = BAKETREE_FEATURED_IDS.map(
  (id) => BAKETREE_DISHES.find((dish) => dish.id === id)!,
);

export function findBaketreeDish(id: string) {
  return BAKETREE_DISHES.find((dish) => dish.id === id);
}

export function baketreeWhatsAppLink(message?: string) {
  const text = encodeURIComponent(
    message ?? `Hi ${BAKETREE.name}, I would like to order from fooody.in/baketree.`,
  );
  return `https://wa.me/91${BAKETREE.whatsapp}?text=${text}`;
}

